apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ss
    metadata:
      labels:
        app: ss
    spec:
      containers:
        - name: ss
          image: srujanatangudu4/ss:v1
          ports:
            - containerPort: 5000


