apiVersion: v1
kind: Service
metadata:
  name: ss-service
spec:
  selector:
    app: ss
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30090
  type: NodePort







